// Generated by https://quicktype.io

export interface CovidFall {
  IdBundesland:         number;
  Bundesland:           string;
  Landkreis:            string;
  Altersgruppe:         string;
  Geschlecht:           string;
  AnzahlFall:           number;
  AnzahlTodesfall:      number;
  ObjectId:             number;
  Meldedatum:           string;
  IdLandkreis:          number;
  Datenstand:           string;
  NeuerFall:            number;
  NeuerTodesfall:       number;
  Refdatum:             string;
  NeuGenesen:           number;
  AnzahlGenesen:        number;
  IstErkrankungsbeginn: number;
  Altersgruppe2:        string;
}
